# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Nack/Desktop/SynLab/project/kkGames/kkGames.cache/wt [current_project]
set_property parent.project_path C:/Users/Nack/Desktop/SynLab/project/kkGames/kkGames.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:basys3:part0:1.1 [current_project]
set_property ip_output_repo c:/Users/Nack/Desktop/SynLab/project/kkGames/kkGames.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/Nack/Desktop/SynLab/project/kkGames/kkGames.srcs/sources_1/new/Attack.v
  C:/Users/Nack/Desktop/SynLab/project/kkGames/kkGames.srcs/sources_1/new/Display.v
  C:/Users/Nack/Desktop/SynLab/project/kkGames/kkGames.srcs/sources_1/new/attack_state_machine.v
  C:/Users/Nack/Desktop/SynLab/project/kkGames/kkGames.srcs/sources_1/new/bullet.v
  C:/Users/Nack/Desktop/SynLab/project/kkGames/kkGames.srcs/sources_1/new/bullet_rom.v
  C:/Users/Nack/Desktop/SynLab/project/kkGames/kkGames.srcs/sources_1/new/dodge.v
  C:/Users/Nack/Desktop/SynLab/project/kkGames/kkGames.srcs/sources_1/new/fight_screen.v
  C:/Users/Nack/Desktop/SynLab/project/kkGames/kkGames.srcs/sources_1/new/flame_monster.v
  C:/Users/Nack/Desktop/SynLab/project/kkGames/kkGames.srcs/sources_1/new/flame_monster_rom.v
  C:/Users/Nack/Desktop/SynLab/project/kkGames/kkGames.srcs/sources_1/new/frame.v
  C:/Users/Nack/Desktop/SynLab/project/kkGames/kkGames.srcs/sources_1/new/game_state_machine.v
  C:/Users/Nack/Desktop/SynLab/project/kkGames/kkGames.srcs/sources_1/new/heart.v
  C:/Users/Nack/Desktop/SynLab/project/kkGames/kkGames.srcs/sources_1/new/heart_rom.v
  C:/Users/Nack/Desktop/SynLab/project/kkGames/kkGames.srcs/sources_1/new/home.v
  C:/Users/Nack/Desktop/SynLab/project/kkGames/kkGames.srcs/sources_1/new/hp_bar.v
  C:/Users/Nack/Desktop/SynLab/project/kkGames/kkGames.srcs/sources_1/new/movable_bar.v
  C:/Users/Nack/Desktop/SynLab/project/kkGames/kkGames.srcs/sources_1/new/uart_receiver.v
  C:/Users/Nack/Desktop/SynLab/project/kkGames/kkGames.srcs/sources_1/new/uart_transmitter.v
  C:/Users/Nack/Desktop/SynLab/project/kkGames/kkGames.srcs/sources_1/new/vga_sync.v
  C:/Users/Nack/Desktop/SynLab/project/kkGames/kkGames.srcs/sources_1/new/white_block_rom.v
  C:/Users/Nack/Desktop/SynLab/project/kkGames/kkGames.srcs/sources_1/new/Game.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Nack/Desktop/SynLab/project/kkGames/kkGames.srcs/constrs_1/new/Basys-3-Master.xdc
set_property used_in_implementation false [get_files C:/Users/Nack/Desktop/SynLab/project/kkGames/kkGames.srcs/constrs_1/new/Basys-3-Master.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top Game -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Game.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Game_utilization_synth.rpt -pb Game_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
